version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api:v1
    deploy:
          labels:
            estudos.azure.api.docker: "Um projeto teste............... boss: Mario .............."
    ports:
        - "8080:80"
    networks:
      - frontend
      - backend
    deploy:
      mode: global
    build:
      context: .
      dockerfile: API/Dockerfile

networks:
  backend:
  frontend:
